[package]
name = "hello-rust"
version = "1.0.0"
edition = "2018"

[dependencies]

#[target.armv7-unknown-linux-gnueabihf]
#rustflags = ["-C", "linker=arm-linux-gnueabihf-gcc", "target-feature=+v7"]
#linker = "arm-poky-gnueabihf-gcc"

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
rustflags = ["-C", "target-feature=+v7"]

[[bin]]
name = "hello"
path = "main.rs"
